import heroImg from "@/assets/hero-leptis.jpg";
import destLeptisArch from "@/assets/dest-leptis-arch.jpg";
import destLeptisTheater from "@/assets/dest-leptis-theater.jpg";
import destLeptisCoast from "@/assets/dest-leptis-coast.jpg";
import destSabratah from "@/assets/dest-sabratha.jpg";
import destSabratahTheater from "@/assets/dest-sabratha-theater.jpg";
import destSabratahTemple from "@/assets/dest-sabratha-temple.jpg";
import destSabratahCoast from "@/assets/dest-sabratha-coast.jpg";
import destTripoli from "@/assets/dest-tripoli.jpg";
import destTripoliCastle from "@/assets/dest-tripoli-castle.jpg";
import destTripoliArch from "@/assets/dest-tripoli-arch.jpg";
import destTripoliMedina from "@/assets/dest-tripoli-medina.jpg";
import destTripoliOldCity from "@/assets/dest-tripoli-old-city.jpg";
import destUbari from "@/assets/dest-ubari.jpg";
import destGhadames from "@/assets/dest-ghadames.jpg";
import destGhadamesAlleys from "@/assets/dest-ghadames-alleys.jpg";
import destGhadamesOasis from "@/assets/dest-ghadames-oasis.jpg";
import destCyrene from "@/assets/dest-cyrene.jpg";
import destCyreneApollo from "@/assets/dest-cyrene-apollo.jpg";
import destCyreneSanctuary from "@/assets/dest-cyrene-sanctuary.jpg";
import destAcacus from "@/assets/dest-acacus.jpg";
import destGharyanCave from "@/assets/dest-gharyan-cave.jpg";
import destGharyanCourtyard from "@/assets/dest-gharyan-courtyard.jpg";
import destKsarDesert from "@/assets/dest-ksar-desert.jpg";
import destKsarNalut from "@/assets/dest-ksar-nalut.jpg";
import destNafusaFortress from "@/assets/dest-nafusa-fortress.jpg";
import destHarborCoast from "@/assets/dest-harbor-coast.jpg";
import destJabalAkhdarPanorama from "@/assets/dest-jabal-akhdar-panorama.jpg";
import destJabalAkhdarForest from "@/assets/dest-jabal-akhdar-forest.jpg";
import destJabalAkhdarBridge from "@/assets/dest-jabal-akhdar-bridge.jpg";
import destJabalAkhdarValley from "@/assets/dest-jabal-akhdar-valley.jpg";
import destJabalAkhdarPass from "@/assets/dest-jabal-akhdar-pass.jpg";
import destUbariGaberoun from "@/assets/dest-ubari-gaberoun.jpg";
import destUbariUmmAlMaa from "@/assets/dest-ubari-ummalmaa.jpg";
import destAcacusArch from "@/assets/dest-acacus-arch.jpg";
import destSaharaDunes from "@/assets/dest-sahara-dunes.jpg";

export type AttractionItem = {
  id: string;
  name: string;
  nameEn: string;
  city: string;
  cityEn: string;
  region: string;
  regionEn: string;
  category: "آثار تاريخية" | "واحات صحراوية" | "طبيعة وجبال" | "مدن قديمة وقلاع";
  categoryEn: "Historical & Ancient Ruins" | "Desert Oases & Dunes" | "Mountains & Nature" | "Old Cities & Fortresses";
  isUnesco: boolean;
  unescoYear?: string;
  img: string;
  gallery: string[];
  description: string;
  descriptionEn: string;
  historySnippet: string;
  historySnippetEn: string;
  rating: number;
  reviewsCount: number;
  hasDailyTrip: boolean;
  departureCity?: "طرابلس" | "بنغازي";
  departureCityEn?: "Tripoli" | "Benghazi";
  departureTime: string;
  departureTimeEn: string;
  entryFee: string;
  entryFeeEn: string;
  bestSeason: string;
  bestSeasonEn: string;
  highlights: string[];
  highlightsEn: string[];
  mapsQuery: string;
  approxTripPrice?: number;
};

export const LIBYAN_ATTRACTIONS: AttractionItem[] = [
  {
    id: "att-leptis",
    name: "مدينة لبدة الكبرى (Leptis Magna)",
    nameEn: "Leptis Magna Ancient City",
    city: "الخمس",
    cityEn: "Al-Khoms",
    region: "المنطقة الغربية (ساحل البحر المتوسط)",
    regionEn: "Western Region (Mediterranean Coast)",
    category: "آثار تاريخية",
    categoryEn: "Historical & Ancient Ruins",
    isUnesco: true,
    unescoYear: "1982",
    img: heroImg,
    gallery: [
      heroImg,
      destSabratah,
      destCyrene,
    ],
    description:
      "أعظم مدينة رومانية محفوظة في حوض البحر المتوسط ومسقط رأس الإمبراطور سيبتيموس سيفيروس. تضم قوس النصر السيفيري البديع، المسرح الروماني المطل على الساحل، حمامات هادريان ذات الأرضيات الرخامية، والسوق البونيقي القديم.",
    descriptionEn:
      "The greatest preserved Roman city in the Mediterranean basin and birthplace of Emperor Septimius Severus. Featuring the grand Severan Arch, colossal Roman theatre overlooking the sea, Hadrianic Baths, and the ancient forum.",
    historySnippet: "بلغت ذروة مجدها وتوسّعها المذهل في عهد السلالة السيفيرية عام 193 ميلادية.",
    historySnippetEn: "Reached its apex of monumental grandeur during the Severan dynasty in 193 AD.",
    rating: 5.0,
    reviewsCount: 480,
    hasDailyTrip: true,
    departureCity: "طرابلس",
    departureCityEn: "Tripoli",
    departureTime: "09:00 صباحاً",
    departureTimeEn: "09:00 AM",
    entryFee: "20 د.ل",
    entryFeeEn: "20 LYD",
    bestSeason: "طوال العام (أكتوبر — مايو الأفضل)",
    bestSeasonEn: "Year-round (Best: Oct — May)",
    highlights: ["قوس سيبتيموس سيفيروس", "المسرح الروماني الساحلي", "حمامات هادريان الفاخرة", "السوق البونيقي التاريخي"],
    highlightsEn: ["Severan Triumphal Arch", "Coastal Roman Theatre", "Hadrianic Thermal Baths", "Ancient Forum & Market"],
    mapsQuery: "Leptis+Magna+Al-Khoms+Libya",
    approxTripPrice: 180,
  },
  {
    id: "att-sabratha",
    name: "مسرح وآثار صبراتة الرومانية",
    nameEn: "Sabratha Roman Theatre & Ruins",
    city: "صبراتة",
    cityEn: "Sabratha",
    region: "المنطقة الغربية (ساحل البحر المتوسط)",
    regionEn: "Western Region (Mediterranean Coast)",
    category: "آثار تاريخية",
    categoryEn: "Historical & Ancient Ruins",
    isUnesco: true,
    unescoYear: "1982",
    img: destSabratah,
    gallery: [
      destSabratah,
      destHarborCoast,
      heroImg,
    ],
    description:
      "واحدة من أهم المدن الأثرية الفينيقية ثم الرومانية على ساحل البحر المتوسط. يشتهر مسرحها الروماني الأيقوني المكون من ثلاثة طوابق من الأعمدة الرخامية البديعة وأعمدة الكورنثية المطلة مباشرة على أمواج البحر.",
    descriptionEn:
      "One of the Mediterranean's finest archaeological sites. World-famous for its three-story coastal Roman theatre reconstructed with 96 Corinthian marble columns facing the azure Mediterranean horizon.",
    historySnippet: "تأسست في القرن السابع قبل الميلاد كمرفأ فينيقي لتبادل التجارة مع أعماق أفريقيا.",
    historySnippetEn: "Founded in the 7th century BC as a Phoenician trading post connecting Africa to the Mediterranean.",
    rating: 4.9,
    reviewsCount: 360,
    hasDailyTrip: true,
    departureCity: "طرابلس",
    departureCityEn: "Tripoli",
    departureTime: "09:00 صباحاً",
    departureTimeEn: "09:00 AM",
    entryFee: "15 د.ل",
    entryFeeEn: "15 LYD",
    bestSeason: "أكتوبر — مايو",
    bestSeasonEn: "October — May",
    highlights: ["المسرح الروماني المكون من 3 طوابق", "معبد إيزيس ومعبد هرقل", "لوحات الفسيفساء البحرية", "المتحف الأثري بصبراتة"],
    highlightsEn: ["3-Tiered Coastal Amphitheatre", "Temples of Isis & Hercules", "Rare Roman Sea Mosaics", "Sabratha Museum"],
    mapsQuery: "Sabratha+Roman+Theater+Libya",
    approxTripPrice: 160,
  },
  {
    id: "att-cyrene",
    name: "قورينا وآثار شحات الإغريقية",
    nameEn: "Cyrene & Ancient Greek Ruins",
    city: "شحات",
    cityEn: "Shahhat",
    region: "الجبل الأخضر (المنطقة الشرقية)",
    regionEn: "Green Mountain (Eastern Region)",
    category: "آثار تاريخية",
    categoryEn: "Historical & Ancient Ruins",
    isUnesco: true,
    unescoYear: "1982",
    img: destJabalAkhdarPanorama,
    gallery: [
      destJabalAkhdarPanorama,
      destCyrene,
      destJabalAkhdarPass,
      destJabalAkhdarValley,
      destHarborCoast,
    ],
    description:
      "أقدم وأعظم مدينة إغريقية في شمال أفريقيا (أثينا أفريقيا)، تقع على حافة هضبة جبلية شاهقة بارتفاع 600 متر مطلة على مزارع وشواطئ سوسة الخضراء، وتضم معبد أبولو، الأكروبوليس، ونبع أبولو المقدس بين الشلالات.",
    descriptionEn:
      "Known as the 'Athens of Africa', the ancient Greek capital perched 600m high atop the lush Green Mountain. Features the Sanctuary of Apollo, the massive Acropolis, Zeus Temple, and panoramic views over the Mediterranean.",
    historySnippet: "تأسست عام 631 قبل الميلاد بواسطة مستوطنين إغريق قادمين من جزيرة ثيرا الإغريقية.",
    historySnippetEn: "Founded in 631 BC by Greek colonists from the island of Thera (modern Santorini).",
    rating: 4.9,
    reviewsCount: 390,
    hasDailyTrip: true,
    departureCity: "بنغازي",
    departureCityEn: "Benghazi",
    departureTime: "09:00 صباحاً",
    departureTimeEn: "09:00 AM",
    entryFee: "15 د.ل",
    entryFeeEn: "15 LYD",
    bestSeason: "سبتمبر — يونيو",
    bestSeasonEn: "September — June",
    highlights: ["بانوراما معبد أبولو والبحر", "معبد زيوس الأضخم في أفريقيا", "المدرج الإغريقي الجبلي", "طبيعة وشلالات الجبل الأخضر"],
    highlightsEn: ["Apollo Sanctuary & Coastal Panorama", "Colossal Temple of Zeus", "Cliffside Greek Theatre", "Green Mountain Waterfalls"],
    mapsQuery: "Cyrene+Shahhat+Libya",
    approxTripPrice: 200,
  },
  {
    id: "att-jabal-akhdar-nature",
    name: "طبيعة وغابات الجبل الأخضر وجسر وادي الكوف",
    nameEn: "Green Mountain Forests & Wadi Al-Kuf Canyon",
    city: "البيضاء وشحات",
    cityEn: "Al-Bayda & Shahhat",
    region: "الجبل الأخضر (المنطقة الشرقية)",
    regionEn: "Green Mountain (Eastern Region)",
    category: "طبيعة وجبال",
    categoryEn: "Mountains & Nature",
    isUnesco: false,
    img: destJabalAkhdarForest,
    gallery: [
      destJabalAkhdarForest,
      destJabalAkhdarBridge,
      destJabalAkhdarValley,
      destJabalAkhdarPass,
      destJabalAkhdarPanorama,
    ],
    description:
      "تعتبر غابات الجبل الأخضر ووادي الكوف من أروع المحميات الطبيعية البكر في شمال أفريقيا. تتسم بغابات الصنوبر والعرعر الفينيقي والبطم، والتربة الحمراء الخصبة، وتضم جسر وادي الكوف الأيقوني العملاق، مع مسارات التخييم والمطلات البانورامية الشاهقة على السهول الزراعية والبحر المتوسط.",
    descriptionEn:
      "The pristine forests of the Green Mountain and Wadi Al-Kuf are among North Africa's most breathtaking natural reserves, featuring dense pine and juniper woodlands, the monumental Wadi Al-Kuf canyon bridge, and panoramic lookouts over coastal plains.",
    historySnippet: "يعد الجبل الأخضر رئة ليبيا الخضراء بمناخه المعتدل شتاءً وصيفاً وجسره المعلق التاريخي الذي صممه المعماري العالمي ريكاردو موراندي.",
    historySnippetEn: "The Green Mountain is Libya's verdant ecological jewel, home to diverse flora, misty mountain passes, and the historic Morandi canyon bridge.",
    rating: 4.95,
    reviewsCount: 420,
    hasDailyTrip: true,
    departureCity: "بنغازي",
    departureCityEn: "Benghazi",
    departureTime: "08:30 صباحاً",
    departureTimeEn: "08:30 AM",
    entryFee: "مجاني",
    entryFeeEn: "Free Access",
    bestSeason: "طوال العام (الربيع والشتاء الأروع بالطبيعة والغيوم)",
    bestSeasonEn: "Year-round (Spring & misty Winter are most scenic)",
    highlights: ["غابات الصنوبر الحلبي والعرعر الفينيقي", "جسر وادي الكوف الأيقوني المعلق", "مطلات عقبة الجبل والسهول الخضراء", "مسارات المشي والتخييم الجبلي"],
    highlightsEn: ["Aleppo Pine & Juniper Forests", "Iconic Wadi Al-Kuf Canyon Bridge", "Mountain Pass Viewpoints", "Eco-Hiking & Camping Trails"],
    mapsQuery: "Wadi+Al-Kuf+Bridge+Libya",
    approxTripPrice: 190,
  },
  {
    id: "att-ghadames",
    name: "مدينة غدامس القديمة (لؤلؤة الصحراء)",
    nameEn: "Old Town of Ghadames (Pearl of the Sahara)",
    city: "غدامس",
    cityEn: "Ghadames",
    region: "الجنوب الغربي (الواحات)",
    regionEn: "Southwestern Oases",
    category: "مدن قديمة وقلاع",
    categoryEn: "Old Cities & Fortresses",
    isUnesco: true,
    unescoYear: "1986",
    img: destGhadames,
    gallery: [
      destGhadames,
      destAcacus,
      destUbari,
    ],
    description:
      "واحة تاريخية مسجلة بالتراث العالمي لليونسكو. تتميز بعمارتها الصحراوية الهندسية الفريدة، الممرات المسقوفة المكيفة طبيعياً لحماية الأهالي من الحرارة، البيوت الطينية المزخرفة بالألوان، وعين الفرس التاريخية التي تروي بساتين النخيل.",
    descriptionEn:
      "An extraordinary UNESCO World Heritage oasis. Celebrated for its unique domed architecture, covered white passages with natural climate cooling, vibrant multi-level Berber mud-brick homes, and the historic Ain Al-Faras spring.",
    historySnippet: "عرفت قدماً باسم 'كيداموس' وكانت محطة التلاقي المركزية لقوافل تجارة الذهب والحرير عبر الصحراء الكبرى.",
    historySnippetEn: "Known in antiquity as Cydamus, the vital crossroads for trans-Saharan gold and silk caravans.",
    rating: 5.0,
    reviewsCount: 340,
    hasDailyTrip: false,
    departureTime: "رحلة أسبوعية / خاصة",
    departureTimeEn: "Weekly / Private Expedition",
    entryFee: "مجاني",
    entryFeeEn: "Free Access",
    bestSeason: "أكتوبر — أبريل",
    bestSeasonEn: "October — April",
    highlights: ["الممرات المسقوفة البيضاء", "عين الفرس التاريخية ونظام السواقي", "المنازل التراثية والمرايا الجدارية", "متحف غدامس للتراث الشعبي"],
    highlightsEn: ["Covered Architectural Alleyways", "Ain Al-Faras Ancient Spring", "Traditional Decorated Rooftops", "Ghadames Folkloric Museum"],
    mapsQuery: "Old+Town+Ghadames+Libya",
  },
  {
    id: "att-ubari",
    name: "بحيرات أوباري الصحراوية وبحيرة قبرعون",
    nameEn: "Ubari Desert Lakes & Gaberoun Oasis",
    city: "أوباري",
    cityEn: "Ubari",
    region: "فزان الصحراوية (الجنوب)",
    regionEn: "Fezzan Sahara (Southern Region)",
    category: "واحات صحراوية",
    categoryEn: "Desert Oases & Dunes",
    isUnesco: false,
    img: destUbariGaberoun,
    gallery: [
      destUbariGaberoun,
      destUbariUmmAlMaa,
      destSaharaDunes,
      destAcacusArch,
    ],
    description:
      "أعجوبة طبيعية استثنائية في قلب رملة أوباري، حيث ترقد بحيرات مائية زرقاء محاطة بأشجار النخيل وسط كثبان رملية ذهبية شاهقة يصل ارتفاعها لأكثر من 120 متراً. تشتهر بحيرة قبرعون بمياهها شديدة الملوحة والتزلج على الرمال وسهرات التخييم الفاخرة.",
    descriptionEn:
      "A stunning natural wonder deep in the Erg Ubari desert. Shimmering sapphire saltwater lakes fringed with green palm groves amidst soaring golden sand dunes over 120m high. Perfect for sandboarding, desert camping, and stargazing.",
    historySnippet: "مستوطنات ومسارات واحات سكنتها قبائل الصحراء الطوارق منذ آلاف السنين.",
    historySnippetEn: "Ancient desert oases inhabited by local Tuareg tribes for thousands of years.",
    rating: 5.0,
    reviewsCount: 420,
    hasDailyTrip: false,
    departureTime: "رحلة مغامرة خاصة / أسبوعية",
    departureTimeEn: "Private 4x4 / Weekly Tour",
    entryFee: "مجاني",
    entryFeeEn: "Free Access",
    bestSeason: "أكتوبر — مارس",
    bestSeasonEn: "October — March",
    highlights: ["بحيرة قبرعون فائقة الملوحة", "كثبان رملية ذهبية عملاقة", "تزلج الرمال وسفاري 4x4", "سهرات شاي الطوارق والمخيمات الفاخرة"],
    highlightsEn: ["High-salinity Gaberoun Lake", "Mega Golden Sand Dunes", "4x4 Desert Dune Bashing", "Authentic Tuareg Camp Nights"],
    mapsQuery: "Gaberoun+Lake+Ubari+Libya",
  },
  {
    id: "att-acacus",
    name: "جبال ورسومات تادرارت أكاكوس الصخرية",
    nameEn: "Tadrart Acacus Rock Art Mountains",
    city: "غات",
    cityEn: "Ghat",
    region: "أقصى الجنوب الغربي (الصحراء الكبرى)",
    regionEn: "Deep Southwestern Sahara",
    category: "طبيعة وجبال",
    categoryEn: "Mountains & Nature",
    isUnesco: true,
    unescoYear: "1985",
    img: destAcacusArch,
    gallery: [
      destAcacusArch,
      destSaharaDunes,
      destUbariGaberoun,
      destUbariUmmAlMaa,
    ],
    description:
      "سلسلة جبلية ساحرة من التكوينات الصخرية والأقواس الطبيعية تضم آلاف النقوش واللوحات الجدارية الملونة التي تعود لأكثر من 14,000 سنة، توثق تحول الصحراء من مروج خضراء مليئة بالزرافات والأفيال إلى الطبيعة الصحراوية الساحرة.",
    descriptionEn:
      "A breathtaking mountain range filled with dramatic natural arches and canyons. Home to thousands of prehistoric rock paintings dating back 14,000+ years, documenting the green savanna era when elephants and giraffes roamed the Sahara.",
    historySnippet: "مدرجة على قائمة التراث العالمي كأحد أقدم وأعظم المتاحف المفتوحة للفن الصخري في تاريخ البشرية.",
    historySnippetEn: "Inscribed as a UNESCO World Heritage site as one of the world's most significant open-air rock art museums.",
    rating: 4.9,
    reviewsCount: 260,
    hasDailyTrip: false,
    departureTime: "رحلة استكشافية خاصة 4x4",
    departureTimeEn: "Special 4x4 Expedition",
    entryFee: "مجاني (يتطلب تصريح ومرشد)",
    entryFeeEn: "Free (Permit & Guide required)",
    bestSeason: "نوفمبر — فبراير",
    bestSeasonEn: "November — February",
    highlights: ["أقواس صخرية وتكوينات جيولوجية نادرة", "نقوش صخرية لحيوانات ما قبل التاريخ", "كهوف ووديان أواندر", "أجواء فلكية ونقاء نجوم استثنائي"],
    highlightsEn: ["Towering Natural Stone Arches", "Prehistoric Animal Rock Paintings", "Wadi Awander Gorges", "Unmatched Dark Sky Stargazing"],
    mapsQuery: "Tadrart+Acacus+Libya",
  },
  {
    id: "att-tripoli-citadel",
    name: "قلعة السراي الحمراء والمدينة القديمة",
    nameEn: "Red Castle (Assaraya Al-Hamra) & Old Tripoli",
    city: "طرابلس",
    cityEn: "Tripoli",
    region: "المنطقة الغربية (العاصمة)",
    regionEn: "Western Region (Capital)",
    category: "مدن قديمة وقلاع",
    categoryEn: "Old Cities & Fortresses",
    isUnesco: false,
    img: destTripoli,
    gallery: [
      destTripoli,
      destTripoliOldCity,
      destHarborCoast,
    ],
    description:
      "قلعة تاريخية مهيبة تشرف على ميناء طرابلس وميدان الشهداء. تحتضن متاحف الآثار الوطنية وجوارها قوس ماركوس أوريليوس الروماني، أزقة أسواق الصاغة والعطارين، وجامع قورجي، ونزل خان فندق الزيت المعماري.",
    descriptionEn:
      "A grand historic citadel overlooking Tripoli harbor and Martyrs' Square. Houses national archaeological treasures, alongside the Roman Arch of Marcus Aurelius, vibrant spice souks, and Ottoman-era Gurgi Mosque.",
    historySnippet: "شهدت تتابع الحضارات الفينيقية، الرومانية، البيزنطية، الإسبانية، وفرسان القديس يوحنا، والعهد العثماني.",
    historySnippetEn: "Witnessed centuries of rule from Phoenicians and Romans to Spaniards, Knights of St. John, and Ottomans.",
    rating: 4.8,
    reviewsCount: 450,
    hasDailyTrip: true,
    departureCity: "طرابلس",
    departureCityEn: "Tripoli",
    departureTime: "09:00 صباحاً",
    departureTimeEn: "09:00 AM",
    entryFee: "10 د.ل",
    entryFeeEn: "10 LYD",
    bestSeason: "طوال العام",
    bestSeasonEn: "Year-round",
    highlights: ["متحف السراي الحمراء الوطني", "قوس ماركوس أوريليوس الروماني (163 م)", "جامع ومئذنة قرجي التاريخية", "أسواق الحرفيين والأزقة التقليدية"],
    highlightsEn: ["Red Castle National Museum", "Marcus Aurelius Roman Arch (163 AD)", "Historic Gurgi Mosque", "Old Souks & Artisan Alleys"],
    mapsQuery: "Red+Castle+Tripoli+Libya",
    approxTripPrice: 120,
  },
  {
    id: "att-gharyan-caves",
    name: "بيوت الحفر التراثية في غريان",
    nameEn: "Gharyan Troglodyte Underground Cave Houses",
    city: "غريان",
    cityEn: "Gharyan",
    region: "جبل نفوسة (المنطقة الغربية)",
    regionEn: "Jebel Nafusa (Western Region)",
    category: "مدن قديمة وقلاع",
    categoryEn: "Old Cities & Fortresses",
    isUnesco: false,
    img: destGharyanCave,
    gallery: [
      destGharyanCave,
      destGharyanCourtyard,
      destKsarDesert,
    ],
    description:
      "عمارة بيئية وهندسية فريدة محفورة في باطن الجبل بعمق يصل لـ 10 أمتار تحافظ على درجات حرارة معتدلة صيفاً وشتاءً، مع ساحات مركزية مفتوحة للسماء تعكس التراث الأمازيغي والجبلي الأصيل.",
    descriptionEn:
      "Extraordinary subterranean vernacular architecture excavated up to 10 meters deep into the earth. Naturally climate-controlled throughout the seasons with sunlit courtyards, embodying the rich Berber heritage of Jebel Nafusa.",
    historySnippet: "تاريخ عريق يعود لمئات السنين حيث استخدم السكان صخور جبل نفوسة لبناء مساكن بيئية مذهلة.",
    historySnippetEn: "Centuries-old troglodyte dwellings carved into mountain rock providing natural thermal comfort and security.",
    rating: 4.9,
    reviewsCount: 310,
    hasDailyTrip: true,
    departureCity: "طرابلس",
    departureCityEn: "Tripoli",
    departureTime: "08:30 صباحاً",
    departureTimeEn: "08:30 AM",
    entryFee: "10 د.ل",
    entryFeeEn: "10 LYD",
    bestSeason: "طوال العام",
    bestSeasonEn: "Year-round",
    highlights: ["حوش الحفر والغرف الدائرية المنحوتة", "الفناء الداخلي المفتوح للشمس", "سوق الفخار اليدوي الشهير بغريان", "منحدرات رأس اللفعة البانورامية"],
    highlightsEn: ["Subterranean Dugout Rooms", "Sunlit Central Courtyard", "Famous Handmade Pottery Souk", "Ras Al-Lafaa Panoramic Peaks"],
    mapsQuery: "Gharyan+Cave+Houses+Libya",
    approxTripPrice: 110,
  },
  {
    id: "att-ksar-nafusa",
    name: "قصور وقلاع الجبل الغربي (نالوت وكاباو)",
    nameEn: "Historic Berber Granary Ksars (Nalut & Kabaw)",
    city: "نالوت / كاباو",
    cityEn: "Nalut / Kabaw",
    region: "جبل نفوسة (المنطقة الغربية)",
    regionEn: "Jebel Nafusa (Western Region)",
    category: "مدن قديمة وقلاع",
    categoryEn: "Old Cities & Fortresses",
    isUnesco: false,
    img: destKsarDesert,
    gallery: [
      destKsarDesert,
      destGharyanCave,
      destGhadames,
    ],
    description:
      "قلاع وحصون حجرية شاهقة ذات طبقات متعددة شيدها الأمازيغ على حواف الجرف لتخزين الحبوب والمحاصيل وزيت الزيتون، تعد شواهد حية على عبقرية العمارة الدفاعية والتراثية.",
    descriptionEn:
      "Towering multi-story fortified cliffside granaries built from stone and plaster by the Berbers to safeguard olive oil and harvests, standing as magnificent medieval engineering marvels.",
    historySnippet: "شيدت في القرون الوسطى كقلاع جماعية ومخازن محصنة ضد الغزوات وتقلبات المناخ.",
    historySnippetEn: "Erected in medieval times as communal fortified storage towers perched on rugged mountain edges.",
    rating: 4.85,
    reviewsCount: 240,
    hasDailyTrip: true,
    departureCity: "طرابلس",
    departureCityEn: "Tripoli",
    departureTime: "07:30 صباحاً",
    departureTimeEn: "07:30 AM",
    entryFee: "10 د.ل",
    entryFeeEn: "10 LYD",
    bestSeason: "أكتوبر — مايو",
    bestSeasonEn: "October — May",
    highlights: ["غرف التخزين متعددة الطبقات", "إطلالات الحافة الجبلية الساحرة", "مسجد كاباو العتيق", "قصر الحاج الدائري المعماري"],
    highlightsEn: ["Multi-tiered Granary Cells", "Spectacular Cliffside Vistas", "Ancient Kabaw Mosque", "Circular Qasr Al-Hajj Fortress"],
    mapsQuery: "Qasr+Nalut+Libya",
    approxTripPrice: 180,
  },
  {
    id: "att-slonta-soussa",
    name: "مدينة أبولونيا ومنحوتات اسلونطة الصخرية",
    nameEn: "Apollonia Coastal Ruins & Slonta Rock Carvings",
    city: "سوسة / شحات",
    cityEn: "Sousa / Shahhat",
    region: "الجبل الأخضر (الساحل الشرقي)",
    regionEn: "Green Mountain (Eastern Coast)",
    category: "طبيعة وجبال",
    categoryEn: "Mountains & Nature",
    isUnesco: false,
    img: destHarborCoast,
    gallery: [
      destHarborCoast,
      destCyrene,
      heroImg,
    ],
    description:
      "مزيج رائع يجمع بين ميناء أبولونيا الإغريقي القديم بمياهه الفيروزية والآثار الغارقة تحت البحر، وكهف اسلونطة الأثري المنحوت في الصخر الجبلي بوجوه ورموز دينية غامضة وفريدة.",
    descriptionEn:
      "A coastal blend of the ancient Greek port of Apollonia with crystal turquoise waters and submerged ruins, paired with the mystical cliff-carved rock sanctuaries and human-shaped faces of Slonta.",
    historySnippet: "كانت أبولونيا الميناء البحري الرئيسي لمملكة قورينا الإغريقية منذ القرن السادس قبل الميلاد.",
    historySnippetEn: "Served as the primary port for the Greek Cyrenaican Kingdom from the 6th century BC.",
    rating: 4.8,
    reviewsCount: 220,
    hasDailyTrip: true,
    departureCity: "بنغازي",
    departureCityEn: "Benghazi",
    departureTime: "09:00 صباحاً",
    departureTimeEn: "09:00 AM",
    entryFee: "15 د.ل",
    entryFeeEn: "15 LYD",
    bestSeason: "أبريل — نوفمبر",
    bestSeasonEn: "April — November",
    highlights: ["ميناء أبولونيا الأثري على البحر", "الآثار والمسارح الغارقة", "منحوتات اسلونطة الجبلية النادرة", "شواطئ سوسة البحرية النقية"],
    highlightsEn: ["Ancient Apollonia Seaport", "Submerged Maritime Ruins", "Mystic Slonta Mountain Carvings", "Pristine Sousa Coast"],
    mapsQuery: "Apollonia+Sousa+Libya",
    approxTripPrice: 190,
  },
  {
    id: "att-villa-silin",
    name: "فيلا سيلين والموزاييك الروماني الفاخر",
    nameEn: "Villa Silin & Roman Seaside Mosaics",
    city: "الخمس",
    cityEn: "Al-Khoms",
    region: "المنطقة الغربية",
    regionEn: "Western Region",
    category: "آثار تاريخية",
    categoryEn: "Historical & Ancient Ruins",
    isUnesco: false,
    img: destSabratah,
    gallery: [
      destSabratah,
      heroImg,
      destTripoli,
    ],
    description:
      "قصر أثري روماني فخم يقع مباشرة على البحر بالقرب من لبدة الكبرى، يشتهر بلوحات الفسيفساء (الموزاييك) الأرضية النادرة الملونة التي تصور سباقات العربات في سيرك روما، والحدائق الرومانية الداخلية المحاطة بالأعمدة.",
    descriptionEn:
      "A luxurious beachfront Roman seaside villa near Leptis Magna. Renowned for its exceptionally preserved, colorful floor mosaics depicting chariot races and mythology, along with peristyle gardens facing the waves.",
    historySnippet: "كانت قصراً صيفياً لأحد كبار نبلاء وسيناتورات لبدة الكبرى في القرن الثاني الميلادي.",
    historySnippetEn: "A lavish coastal retreat for a wealthy Roman senator of Leptis Magna during the 2nd century AD.",
    rating: 4.8,
    reviewsCount: 180,
    hasDailyTrip: true,
    departureCity: "طرابلس",
    departureCityEn: "Tripoli",
    departureTime: "09:00 صباحاً",
    departureTimeEn: "09:00 AM",
    entryFee: "10 د.ل",
    entryFeeEn: "10 LYD",
    bestSeason: "طوال العام",
    bestSeasonEn: "Year-round",
    highlights: ["لوحات فسيفساء سباق العربات النادرة", "إطلالة شاطئية رومانية مباشرة", "غرف الحمامات الرخامية القديمة", "تدرج معماري محفوظ بامتياز"],
    highlightsEn: ["Famous Chariot Race Mosaics", "Direct Seaside Roman Terrace", "Preserved Thermal Baths", "Intact Columned Courtyards"],
    mapsQuery: "Villa+Silin+Al-Khoms+Libya",
    approxTripPrice: 160,
  },
];

export type CityDestinationItem = {
  id: string;
  name: string;
  nameEn: string;
  shortName: string;
  shortNameEn: string;
  subtitle: string;
  subtitleEn: string;
  region: string;
  categoryTag: string;
  categoryTagEn: string;
  img: string;
  photos: string[];
  videoUrl?: string;
  mapQuery: string;
  rating: number;
  reviewsCount: number;
  ratingLabel: string;
  ratingLabelEn: string;
  hasDailyTrip: boolean;
  hasWeeklyTrip: boolean;
  hasPrivateTrip: boolean;
  startPriceLYD: number;
  landmarksCount: number;
  description: string;
  descriptionEn: string;
  dailyTripsInfo: string;
  dailyTripsInfoEn: string;
  highlights: string[];
};

export const LIBYAN_CITIES: CityDestinationItem[] = [
  {
    id: "city-khoms",
    name: "مدينة الخمس (لبدة الكبرى)",
    nameEn: "Al-Khoms City (Leptis Magna)",
    shortName: "الخمس",
    shortNameEn: "Al-Khoms",
    subtitle: "عاصمة الآثار الرومانية الساحلية",
    subtitleEn: "Capital of Coastal Roman Heritage",
    region: "المنطقة الغربية",
    categoryTag: "ساحلية ورومانية تاريخية",
    categoryTagEn: "Coastal & Historic Roman",
    img: heroImg,
    photos: [
      heroImg,
      destLeptisArch,
      destLeptisTheater,
      destLeptisCoast,
    ],
    mapQuery: "Leptis+Magna+Al+Khoms+Libya",
    rating: 4.9,
    reviewsCount: 480,
    ratingLabel: "استثنائي جداً",
    ratingLabelEn: "Exceptional",
    hasDailyTrip: true,
    hasWeeklyTrip: false,
    hasPrivateTrip: true,
    startPriceLYD: 180,
    landmarksCount: 12,
    description: "مدينة الخمس الساحلية تحتضن أعظم مدينة رومانية محفوظة في البحر المتوسط (لبدة الكبرى) وفيلا سيلين وميناء لبدة القديم.",
    descriptionEn: "Al-Khoms hosts Leptis Magna, the finest preserved Roman city in the Mediterranean, alongside Villa Silin and the ancient harbor.",
    dailyTripsInfo: "رحلة يومية منتظمة تنطلق من العاصمة طرابلس يومياً الساعة 09:00 صباحاً في حافلة سياحية مكيفة شاملة تذاكر الدخول للموقع الأثري والمرشد السياحي المعتمد ووجبة الغداء.",
    dailyTripsInfoEn: "Daily departures from Tripoli at 09:00 AM in air-conditioned coaches, including site tickets, certified guide, and lunch.",
    highlights: ["آثار لبدة الكبرى وقوس سيفيروس", "المسرح الروماني الساحلي الأثري", "فيلا سيلين وموزاييك العربات", "ميناء ومخازن لبدة البحرية القديمة"],
  },
  {
    id: "city-tripoli",
    name: "طرابلس (عروس البحر)",
    nameEn: "Tripoli (Bride of the Sea)",
    shortName: "طرابلس",
    shortNameEn: "Tripoli",
    subtitle: "العاصمة والمدينة القديمة التاريخية",
    subtitleEn: "Capital & Historic Old Citadel",
    region: "المنطقة الغربية",
    categoryTag: "ساحلية وإسلامية عريقة",
    categoryTagEn: "Coastal & Historic Citadel",
    img: destTripoli,
    photos: [
      destTripoli,
      destTripoliCastle,
      destTripoliArch,
      destTripoliMedina,
    ],
    mapQuery: "Red+Castle+Tripoli+Libya",
    rating: 4.8,
    reviewsCount: 450,
    ratingLabel: "ممتاز جداً",
    ratingLabelEn: "Wonderful",
    hasDailyTrip: true,
    hasWeeklyTrip: false,
    hasPrivateTrip: true,
    startPriceLYD: 120,
    landmarksCount: 18,
    description: "تتميز طرابلس بقلعة السراي الحمراء التاريخية، قوس ماركوس أوريليوس الروماني، أزقة أسواق الصاغة، والمباني المعمارية الإيطالية والعثمانية.",
    descriptionEn: "Features the iconic Red Castle Citadel, Marcus Aurelius Arch, vibrant artisan souks, and historic Mediterranean harbors.",
    dailyTripsInfo: "جولات يومية مكثفة تنطلق يومياً الساعة 09:00 ص من ميدان الشهداء تشمل زيارة السراي الحمراء، قوس ماركوس أوريليوس، وأسواق المدينة القديمة مع وجبة غداء تراثية.",
    dailyTripsInfoEn: "Daily tours departing at 09:00 AM from Martyrs' Square covering Red Castle, Marcus Aurelius Arch, and old souks.",
    highlights: ["قلعة السراي الحمراء التاريخية", "قوس الإمبراطور ماركوس أوريليوس", "أسواق الصاغة وسوق الحرير القديم", "جامع أحمد باشا القره مانلي العريق"],
  },
  {
    id: "city-sabratha",
    name: "مدينة صبراتة التاريخية",
    nameEn: "Sabratha Ancient City",
    shortName: "صبراتة",
    shortNameEn: "Sabratha",
    subtitle: "جوهرة الساحل الفينيقي والروماني",
    subtitleEn: "Jewel of Phoenician & Roman Coast",
    region: "المنطقة الغربية",
    categoryTag: "ساحلية ورومانية تاريخية",
    categoryTagEn: "Coastal & Historic Roman",
    img: destSabratah,
    photos: [
      destSabratah,
      destSabratahTheater,
      destSabratahTemple,
      destSabratahCoast,
    ],
    mapQuery: "Sabratha+Roman+Theatre+Libya",
    rating: 4.9,
    reviewsCount: 360,
    ratingLabel: "ممتاز جداً",
    ratingLabelEn: "Wonderful",
    hasDailyTrip: true,
    hasWeeklyTrip: false,
    hasPrivateTrip: true,
    startPriceLYD: 160,
    landmarksCount: 8,
    description: "تضم أعظم مسرح روماني ساحلي مكون من ثلاثة طوابق من الأعمدة الكورنثية المطلة على البحر مباشرة ومعابد إيزيس وهرقل.",
    descriptionEn: "Home to the famous 3-tiered coastal Roman theatre, ancient Phoenician harbour ruins, and stunning sea mosaic temples.",
    dailyTripsInfo: "تنطلق رحلات يومية من طرابلس الساعة 09:00 ص إلى مسرح وآثار صبراتة الساحلية والمتحف الأثري شاملة المرشد والنقل الفاخر.",
    dailyTripsInfoEn: "Daily trips depart from Tripoli at 09:00 AM to Sabratha Roman Theatre and archaeological museum.",
    highlights: ["المسرح الروماني ذو الطبقات الثلاث", "معبد إيزيس ومعبد هرقل الأثري", "متحف الفسيفساء والمرفأ الفينيقي", "الحمامات الرومانية الشاطئية المطلة على البحر"],
  },
  {
    id: "city-shahhat",
    name: "مدينة شحات (قورينا)",
    nameEn: "Shahhat City (Cyrene)",
    shortName: "شحات",
    shortNameEn: "Shahhat",
    subtitle: "أثينا أفريقيا فوق الجبل الأخضر",
    subtitleEn: "Athens of Africa atop Green Mountain",
    region: "الجبل الأخضر",
    categoryTag: "جبلية وإغريقية أثرية",
    categoryTagEn: "Mountain & Ancient Greek",
    img: destJabalAkhdarPanorama,
    photos: [
      destJabalAkhdarPanorama,
      destCyreneApollo,
      destCyreneSanctuary,
      destCyrene,
    ],
    mapQuery: "Cyrene+Shahhat+Libya",
    rating: 4.9,
    reviewsCount: 390,
    ratingLabel: "استثنائي",
    ratingLabelEn: "Exceptional",
    hasDailyTrip: true,
    hasWeeklyTrip: false,
    hasPrivateTrip: true,
    startPriceLYD: 200,
    landmarksCount: 14,
    description: "مدينة إغريقية تاريخية بارتفاع 600 متر على الجبل الأخضر، تضم معبد أبولو ونبعه المقدس، معبد زيوس العملاق، وشلالات الطبيعة.",
    descriptionEn: "Ancient Greek capital perched 600m high atop the lush Green Mountain. Features Apollo Sanctuary, Zeus Temple, and mountain waterfalls.",
    dailyTripsInfo: "رحلات يومية منتظمة تنطلق من مدينة بنغازي الساعة 09:00 صباحاً نحو الجبل الأخضر وشحات، شاملة زيارة معبد أبولو والأكروبوليس والشلالات.",
    dailyTripsInfoEn: "Daily trips departing Benghazi at 09:00 AM to Green Mountain, Cyrene ruins, and Apollo sanctuary.",
    highlights: ["معبد ونبع أبولو المقدس", "معبد زيوس الأضخم في شمال أفريقيا", "أكروبوليس قورينا والمدرج الإغريقي", "شلالات وادي المنصورة بين الغابات"],
  },
  {
    id: "city-jabal-akhdar",
    name: "الجبل الأخضر ووادي الكوف",
    nameEn: "Green Mountain & Wadi Al-Kuf",
    shortName: "الجبل الأخضر",
    shortNameEn: "Green Mountain",
    subtitle: "غابات الصنوبر وجسر وادي الكوف الأيقوني",
    subtitleEn: "Pine Forests & Iconic Canyon Bridge",
    region: "المنطقة الشرقية",
    categoryTag: "طبيعة ومحميات جبلية",
    categoryTagEn: "Nature & Mountain Reserves",
    img: destJabalAkhdarForest,
    photos: [
      destJabalAkhdarForest,
      destJabalAkhdarBridge,
      destJabalAkhdarPanorama,
      destJabalAkhdarValley,
    ],
    mapQuery: "Wadi+Al-Kuf+Bridge+Libya",
    rating: 4.95,
    reviewsCount: 420,
    ratingLabel: "وجهة ساحرة",
    ratingLabelEn: "Magical Destination",
    hasDailyTrip: true,
    hasWeeklyTrip: true,
    hasPrivateTrip: true,
    startPriceLYD: 190,
    landmarksCount: 16,
    description: "أكبر محمية طبيعية خضراء في ليبيا، تتميز بغابات الصنوبر الشاهقة، جسر وادي الكوف المعلق، ومسارات المشي والاستجمام في الهواء الجبلي النقي.",
    descriptionEn: "Libya's premier green natural reserve, featuring dense pine woodlands, caves, the famous Wadi Al-Kuf suspension bridge, and scenic mountain trails.",
    dailyTripsInfo: "رحلات يومية وأسبوعية تنطلق من بنغازي نحو غابات ووديان الجبل الأخضر وجسر وادي الكوف ومطلات عقبة الجبل.",
    dailyTripsInfoEn: "Daily and weekly tours departing Benghazi exploring the Green Mountain pine forests, canyon bridge, and lookouts.",
    highlights: ["جسر وادي الكوف المعلق", "غابات الصنوبر والعرعر الطبيعية", "مطلات عقبة الجبل على السهول الزراعية", "أودية المنصورة والينابيع الجبلية"],
  },
  {
    id: "city-ghadames",
    name: "مدينة غدامس (لؤلؤة الصحراء)",
    nameEn: "Ghadames Old Town (Sahara Pearl)",
    shortName: "غدامس",
    shortNameEn: "Ghadames",
    subtitle: "معمار صحراوي مسجل بالتراث العالمي",
    subtitleEn: "UNESCO Desert Oasis Architecture",
    region: "الجنوب الغربي",
    categoryTag: "صحراوية وتراث اليونسكو",
    categoryTagEn: "Desert & UNESCO Heritage",
    img: destGhadames,
    photos: [
      destGhadames,
      destGhadamesAlleys,
      destGhadamesOasis,
      destSaharaDunes,
    ],
    mapQuery: "Ghadames+Old+Town+Libya",
    rating: 5.0,
    reviewsCount: 340,
    ratingLabel: "ممتاز وباهر",
    ratingLabelEn: "Out-of-this-World",
    hasDailyTrip: false,
    hasWeeklyTrip: true,
    hasPrivateTrip: true,
    startPriceLYD: 350,
    landmarksCount: 10,
    description: "واحة تاريخية بالممرات المسقوفة المكيفة بيئياً، المنازل الطينية الملونة، عين الفرس التاريخية، وبساتين النخيل في عمق الصحراء.",
    descriptionEn: "Historic UNESCO oasis celebrated for covered cool alleys, colorful Berber homes, Ain Al-Faras spring, and rich desert folklore.",
    dailyTripsInfo: "رحلة أسبوعية / خاصة استكشافية لمدة 3 أيام تنطلق نهاية كل أسبوع شاملة الإقامة في المنازل التراثية والوجبات الغدامسية وجولات عين الفرس والممر المسقوف.",
    dailyTripsInfoEn: "3-day weekly / private expedition including traditional home stays, desert meals, and guided oasis tours.",
    highlights: ["الممرات المسقوفة المكيفة بيئياً", "عين الفرس الكبريتية التاريخية", "المنازل التراثية البربرية الملونة", "متحف التراث وواحات بساتين النخيل"],
  },
  {
    id: "city-ubari",
    name: "واحة أوباري وبحيرة قبرعون",
    nameEn: "Ubari Oases & Gaberoun Lake",
    shortName: "أوباري",
    shortNameEn: "Ubari",
    subtitle: "بحيرات زرقاء وسط الكثبان الذهبية",
    subtitleEn: "Sapphire Lakes in Golden Dunes",
    region: "فزان الصحراوية",
    categoryTag: "واحات صحراوية وبحيرات طبيعية",
    categoryTagEn: "Sahara Oasis & Nature Lakes",
    img: destUbariGaberoun,
    photos: [
      destUbariGaberoun,
      destUbariUmmAlMaa,
      destUbari,
      destSaharaDunes,
    ],
    mapQuery: "Gaberoun+Lake+Ubari+Libya",
    rating: 5.0,
    reviewsCount: 420,
    ratingLabel: "استثنائي باهر",
    ratingLabelEn: "Unmatched",
    hasDailyTrip: false,
    hasWeeklyTrip: true,
    hasPrivateTrip: true,
    startPriceLYD: 400,
    landmarksCount: 7,
    description: "أعجوبة طبيعية ترقد بها بحيرات زرقاء فائقة الملوحة بين كثبان رملية بارتفاع 120 متراً مع تزلج الرمال ومخيمات الطوارق.",
    descriptionEn: "Nature wonder with deep blue lakes nestled in 120m high golden dunes. Ideal for dune bashing, sandboarding, and Tuareg nights.",
    dailyTripsInfo: "رحلات مغامرة أسبوعية وخاصة سيارات 4x4 عبر كثبان رملة أوباري، شاملة التزلج على الرمال وتجربة مياه قبرعون ومخيمات الشاي الطوارقية.",
    dailyTripsInfoEn: "4x4 weekly dune adventure including sandboarding, Gaberoun salt lake, and Tuareg camp tea nights.",
    highlights: ["بحيرة قبرعون فائقة الملوحة والجمال", "كثبان بحر الرمال العظيم (ارتفاع 120م)", "واحات أم الماء والمفرو والطرونة", "مخيمات الطوارق وسفاري الدفع الرباعي 4x4"],
  },
  {
    id: "city-ghat",
    name: "مدينة غات وجبال أكاكوس",
    nameEn: "Ghat City & Acacus Mountains",
    shortName: "غات",
    shortNameEn: "Ghat",
    subtitle: "متحف الفن الصخري الطبيعي المفتوح",
    subtitleEn: "Open-Air Prehistoric Rock Art Museum",
    region: "أقصى الجنوب الغربي",
    categoryTag: "جبال صحراوية ونقوش تاريخية",
    categoryTagEn: "Desert Mountains & Rock Art",
    img: destAcacusArch,
    photos: [
      destAcacusArch,
      destAcacus,
      destSaharaDunes,
      destKsarDesert,
    ],
    mapQuery: "Acacus+Mountains+Ghat+Libya",
    rating: 4.9,
    reviewsCount: 260,
    ratingLabel: "استثنائي",
    ratingLabelEn: "Exceptional",
    hasDailyTrip: false,
    hasWeeklyTrip: true,
    hasPrivateTrip: true,
    startPriceLYD: 450,
    landmarksCount: 9,
    description: "تضم جبال وتكوينات أكاكوس الصخرية ونقوش ما قبل التاريخ التي تعود لأكثر من 14,000 سنة وقلعة غات التاريخية.",
    descriptionEn: "Gate to the UNESCO Tadrart Acacus prehistoric rock paintings, natural arches, Awander canyons, and historic Ghat fortress.",
    dailyTripsInfo: "رحلات خاصة وأسبوعية استكشافية 4x4 إلى جبال ورسومات أكاكوس الصخرية ووادي أواندر، مع تصاريح ومرافقين محليين وتخييم تحت النجوم.",
    dailyTripsInfoEn: "4x4 weekly / private expeditions to Acacus rock art, Awander canyon, camping under the desert stars.",
    highlights: ["رسومات ونقوش أكاكوس (14,000 سنة)", "الأقواس والجسور الصخرية الطبيعية العملاقة", "قلعة غات الطينية والمدينة العتيقة", "وادي أواندر وعيون الصحراء العذبة"],
  },
  {
    id: "city-gharyan",
    name: "مدينة غريان (جبل نفوسة)",
    nameEn: "Gharyan City (Jebel Nafusa)",
    shortName: "غريان",
    shortNameEn: "Gharyan",
    subtitle: "عاصمة بيوت الحفر والفخار التراثي",
    subtitleEn: "Capital of Cave Houses & Pottery",
    region: "جبل نفوسة",
    categoryTag: "جبلية وتراث أصيل",
    categoryTagEn: "Mountain & Heritage",
    img: destGharyanCave,
    photos: [
      destGharyanCave,
      destGharyanCourtyard,
      destNafusaFortress,
      destKsarDesert,
    ],
    mapQuery: "Gharyan+Libya",
    rating: 4.9,
    reviewsCount: 310,
    ratingLabel: "ممتاز جداً",
    ratingLabelEn: "Wonderful",
    hasDailyTrip: true,
    hasWeeklyTrip: false,
    hasPrivateTrip: true,
    startPriceLYD: 110,
    landmarksCount: 8,
    description: "مدينة جبلية عريقة تشتهر ببيوت الحفر التراثية الفريدة المحفورة تحت الأرض، وأسواق الفخار اليدوي الشهيرة، وإطلالات رأس اللفعة الشاهقة.",
    descriptionEn: "Historic mountain town world-famous for subterranean troglodyte cave dwellings, handmade pottery kilns, and cliffside panoramas.",
    dailyTripsInfo: "رحلات يومية منتظمة تنطلق من طرابلس الساعة 08:30 صباحاً شاملة زيارة بيوت الحفر، وورش الفخار، مع وجبة غداء جبلية تقليدية.",
    dailyTripsInfoEn: "Daily departures from Tripoli at 08:30 AM including cave houses tour, pottery workshops, and traditional lunch.",
    highlights: ["بيوت الحفر التراثية المحفورة في الجبل", "ورش ومصانع الفخار والخزف التقليدي", "إطلالات رأس اللفعة الجبلية الخلابة", "أكلات جبلية أصيلة وزيت زيتون نفوسي"],
  },
  {
    id: "city-nalut",
    name: "نالوت وقصور الجبل الغربي",
    nameEn: "Nalut & Berber Mountain Ksars",
    shortName: "نالوت",
    shortNameEn: "Nalut",
    subtitle: "قلاع وقصور تخزين الحبوب الأمازيغية",
    subtitleEn: "Historic Berber Cliffside Granaries",
    region: "جبل نفوسة",
    categoryTag: "قلاع وتراث تاريخي",
    categoryTagEn: "Fortress & History",
    img: destKsarDesert,
    photos: [
      destKsarDesert,
      destKsarNalut,
      destNafusaFortress,
      destGharyanCourtyard,
    ],
    mapQuery: "Qasr+Nalut+Libya",
    rating: 4.85,
    reviewsCount: 240,
    ratingLabel: "تاريخي أصيل",
    ratingLabelEn: "Authentic Heritage",
    hasDailyTrip: true,
    hasWeeklyTrip: true,
    hasPrivateTrip: true,
    startPriceLYD: 180,
    landmarksCount: 6,
    description: "تضم أعظم القصور الأمازيغية التاريخية لتخزين المحاصيل (قصر نالوت وقصر كاباو وقصر الحاج) المعلقة فوق حواف الجبل السحيقة.",
    descriptionEn: "Home to the greatest medieval Berber granaries and storage towers (Nalut, Kabaw, and Qasr Al-Hajj) dramatically perched over cliff edges.",
    dailyTripsInfo: "رحلات جبلية متكاملة لزيارة قصر نالوت وقصر كاباو ومسجدها العتيق مع إطلالات بانورامية على السهل والجبال.",
    dailyTripsInfoEn: "Full-day mountain tours visiting Nalut and Kabaw ksars with panoramic clifftop views.",
    highlights: ["قصر نالوت الأثري ذو الطبقات الست", "قصر كاباو والمسجد العتيق", "قصر الحاج الدائري الفريد", "إطلالات الحافة الجبلية الشاهقة"],
  },
];
