/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AttractionsRouteImport } from './routes/attractions'
import { Route as GuidesRouteImport } from './routes/guides'
import { Route as HotelsRouteImport } from './routes/hotels'
import { Route as RestaurantsRouteImport } from './routes/restaurants'
import { Route as SupportRouteImport } from './routes/support'
import { Route as TransportRouteImport } from './routes/transport'
import { Route as TripsRouteImport } from './routes/trips'
import { Route as AuthLoginRouteImport } from './routes/auth.login'
import { Route as AuthSignupRouteImport } from './routes/auth.signup'
import { Route as DashboardAdminRouteImport } from './routes/dashboard.admin'
import { Route as DashboardDriverRouteImport } from './routes/dashboard.driver'
import { Route as DashboardGuideRouteImport } from './routes/dashboard.guide'
import { Route as DashboardTouristRouteImport } from './routes/dashboard.tourist'
import { Route as DashboardTransportRouteImport } from './routes/dashboard.transport'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AttractionsRoute = AttractionsRouteImport.update({
  id: '/attractions',
  path: '/attractions',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidesRoute = GuidesRouteImport.update({
  id: '/guides',
  path: '/guides',
  getParentRoute: () => rootRouteImport,
} as any)
const HotelsRoute = HotelsRouteImport.update({
  id: '/hotels',
  path: '/hotels',
  getParentRoute: () => rootRouteImport,
} as any)
const RestaurantsRoute = RestaurantsRouteImport.update({
  id: '/restaurants',
  path: '/restaurants',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const TransportRoute = TransportRouteImport.update({
  id: '/transport',
  path: '/transport',
  getParentRoute: () => rootRouteImport,
} as any)
const TripsRoute = TripsRouteImport.update({
  id: '/trips',
  path: '/trips',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignupRoute = AuthSignupRouteImport.update({
  id: '/auth/signup',
  path: '/auth/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardAdminRoute = DashboardAdminRouteImport.update({
  id: '/dashboard/admin',
  path: '/dashboard/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardDriverRoute = DashboardDriverRouteImport.update({
  id: '/dashboard/driver',
  path: '/dashboard/driver',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardGuideRoute = DashboardGuideRouteImport.update({
  id: '/dashboard/guide',
  path: '/dashboard/guide',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardTouristRoute = DashboardTouristRouteImport.update({
  id: '/dashboard/tourist',
  path: '/dashboard/tourist',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardTransportRoute = DashboardTransportRouteImport.update({
  id: '/dashboard/transport',
  path: '/dashboard/transport',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/attractions': typeof AttractionsRoute
  '/guides': typeof GuidesRoute
  '/hotels': typeof HotelsRoute
  '/restaurants': typeof RestaurantsRoute
  '/support': typeof SupportRoute
  '/transport': typeof TransportRoute
  '/trips': typeof TripsRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/signup': typeof AuthSignupRoute
  '/dashboard/admin': typeof DashboardAdminRoute
  '/dashboard/driver': typeof DashboardDriverRoute
  '/dashboard/guide': typeof DashboardGuideRoute
  '/dashboard/tourist': typeof DashboardTouristRoute
  '/dashboard/transport': typeof DashboardTransportRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/attractions': typeof AttractionsRoute
  '/guides': typeof GuidesRoute
  '/hotels': typeof HotelsRoute
  '/restaurants': typeof RestaurantsRoute
  '/support': typeof SupportRoute
  '/transport': typeof TransportRoute
  '/trips': typeof TripsRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/signup': typeof AuthSignupRoute
  '/dashboard/admin': typeof DashboardAdminRoute
  '/dashboard/driver': typeof DashboardDriverRoute
  '/dashboard/guide': typeof DashboardGuideRoute
  '/dashboard/tourist': typeof DashboardTouristRoute
  '/dashboard/transport': typeof DashboardTransportRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/attractions': typeof AttractionsRoute
  '/guides': typeof GuidesRoute
  '/hotels': typeof HotelsRoute
  '/restaurants': typeof RestaurantsRoute
  '/support': typeof SupportRoute
  '/transport': typeof TransportRoute
  '/trips': typeof TripsRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/signup': typeof AuthSignupRoute
  '/dashboard/admin': typeof DashboardAdminRoute
  '/dashboard/driver': typeof DashboardDriverRoute
  '/dashboard/guide': typeof DashboardGuideRoute
  '/dashboard/tourist': typeof DashboardTouristRoute
  '/dashboard/transport': typeof DashboardTransportRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/attractions'
    | '/guides'
    | '/hotels'
    | '/restaurants'
    | '/support'
    | '/transport'
    | '/trips'
    | '/auth/login'
    | '/auth/signup'
    | '/dashboard/admin'
    | '/dashboard/driver'
    | '/dashboard/guide'
    | '/dashboard/tourist'
    | '/dashboard/transport'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/attractions'
    | '/guides'
    | '/hotels'
    | '/restaurants'
    | '/support'
    | '/transport'
    | '/trips'
    | '/auth/login'
    | '/auth/signup'
    | '/dashboard/admin'
    | '/dashboard/driver'
    | '/dashboard/guide'
    | '/dashboard/tourist'
    | '/dashboard/transport'
  id:
    | '__root__'
    | '/'
    | '/attractions'
    | '/guides'
    | '/hotels'
    | '/restaurants'
    | '/support'
    | '/transport'
    | '/trips'
    | '/auth/login'
    | '/auth/signup'
    | '/dashboard/admin'
    | '/dashboard/driver'
    | '/dashboard/guide'
    | '/dashboard/tourist'
    | '/dashboard/transport'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AttractionsRoute: typeof AttractionsRoute
  GuidesRoute: typeof GuidesRoute
  HotelsRoute: typeof HotelsRoute
  RestaurantsRoute: typeof RestaurantsRoute
  SupportRoute: typeof SupportRoute
  TransportRoute: typeof TransportRoute
  TripsRoute: typeof TripsRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthSignupRoute: typeof AuthSignupRoute
  DashboardAdminRoute: typeof DashboardAdminRoute
  DashboardDriverRoute: typeof DashboardDriverRoute
  DashboardGuideRoute: typeof DashboardGuideRoute
  DashboardTouristRoute: typeof DashboardTouristRoute
  DashboardTransportRoute: typeof DashboardTransportRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/attractions': {
      id: '/attractions'
      path: '/attractions'
      fullPath: '/attractions'
      preLoaderRoute: typeof AttractionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides': {
      id: '/guides'
      path: '/guides'
      fullPath: '/guides'
      preLoaderRoute: typeof GuidesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hotels': {
      id: '/hotels'
      path: '/hotels'
      fullPath: '/hotels'
      preLoaderRoute: typeof HotelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/restaurants': {
      id: '/restaurants'
      path: '/restaurants'
      fullPath: '/restaurants'
      preLoaderRoute: typeof RestaurantsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transport': {
      id: '/transport'
      path: '/transport'
      fullPath: '/transport'
      preLoaderRoute: typeof TransportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trips': {
      id: '/trips'
      path: '/trips'
      fullPath: '/trips'
      preLoaderRoute: typeof TripsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/signup': {
      id: '/auth/signup'
      path: '/auth/signup'
      fullPath: '/auth/signup'
      preLoaderRoute: typeof AuthSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/admin': {
      id: '/dashboard/admin'
      path: '/dashboard/admin'
      fullPath: '/dashboard/admin'
      preLoaderRoute: typeof DashboardAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/driver': {
      id: '/dashboard/driver'
      path: '/dashboard/driver'
      fullPath: '/dashboard/driver'
      preLoaderRoute: typeof DashboardDriverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/guide': {
      id: '/dashboard/guide'
      path: '/dashboard/guide'
      fullPath: '/dashboard/guide'
      preLoaderRoute: typeof DashboardGuideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/tourist': {
      id: '/dashboard/tourist'
      path: '/dashboard/tourist'
      fullPath: '/dashboard/tourist'
      preLoaderRoute: typeof DashboardTouristRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/transport': {
      id: '/dashboard/transport'
      path: '/dashboard/transport'
      fullPath: '/dashboard/transport'
      preLoaderRoute: typeof DashboardTransportRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AttractionsRoute: AttractionsRoute,
  GuidesRoute: GuidesRoute,
  HotelsRoute: HotelsRoute,
  RestaurantsRoute: RestaurantsRoute,
  SupportRoute: SupportRoute,
  TransportRoute: TransportRoute,
  TripsRoute: TripsRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthSignupRoute: AuthSignupRoute,
  DashboardAdminRoute: DashboardAdminRoute,
  DashboardDriverRoute: DashboardDriverRoute,
  DashboardGuideRoute: DashboardGuideRoute,
  DashboardTouristRoute: DashboardTouristRoute,
  DashboardTransportRoute: DashboardTransportRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
